name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore ./GF.Library.sln 
    - name: Build with dotnet
      run: dotnet build ./GF.Library.sln --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test ./GF.Library.sln --no-restore --verbosity normal
